### ISSUE TITLE
 called without required argument 'cargoSha256' while running nox-review

### ISSUE THREAD

**Issue by andir** [mozilla/nixpkgs-mozilla#80]
@nbp: as discussed during FOSDEM here is the issue I tried to describe.

This issue occurs with all PRs that I am testing while the mozilla overlay exists in `.config/nixpkgs/overlays/nixpkgs-mozilla`.

I can use the overlay (outside of the scope of nox) just fine.

```shell
# nix-shell  -p nox --run "nox-review pr 33680"                                                                                                                                                    /home/andi
=== Reviewing PR 33680 : notmuch: 0.25.3 -> 0.26
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
error: while querying the derivation named 'servo-latest':
while evaluating the attribute 'buildInputs' of the derivation 'servo-latest' at /home/andi/.nox/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating 'getOutput' at /home/andi/.nox/nixpkgs/lib/attrsets.nix:450:23, called from undefined position:
while evaluating anonymous function at /home/andi/.nox/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:97:17, called from undefined position:
anonymous function at /home/andi/.nox/nixpkgs/pkgs/build-support/rust/default.nix:7:1 called without required argument 'cargoSha256', at /home/andi/.config/nixpkgs/overlays/nixpkgs-mozilla/pkgs/servo/default.nix:43:15
Traceback (most recent call last):
  File "/nix/store/hn9sswpyglcwjgyg5g2jnrq1n2f50rfz-nox-0.0.6/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/y6g9fafk91jpnnns7wl3njhrjqmam5kj-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/y6g9fafk91jpnnns7wl3njhrjqmam5kj-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/y6g9fafk91jpnnns7wl3njhrjqmam5kj-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/y6g9fafk91jpnnns7wl3njhrjqmam5kj-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/y6g9fafk91jpnnns7wl3njhrjqmam5kj-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/y6g9fafk91jpnnns7wl3njhrjqmam5kj-python3.6-click-6.7/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/hn9sswpyglcwjgyg5g2jnrq1n2f50rfz-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 71, in _
    f(*args, **kwargs)
  File "/nix/store/hn9sswpyglcwjgyg5g2jnrq1n2f50rfz-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 184, in review_pr
    attrs = differences(packages_for_sha(base),
  File "/nix/store/81lwc481132mx4l83kwbpby331y2j5vv-python3.6-dogpile.cache-0.6.4/lib/python3.6/site-packages/dogpile/cache/region.py", line 1231, in decorate
    should_cache_fn)
  File "/nix/store/81lwc481132mx4l83kwbpby331y2j5vv-python3.6-dogpile.cache-0.6.4/lib/python3.6/site-packages/dogpile/cache/region.py", line 833, in get_or_create
    async_creator) as value:
  File "/nix/store/81lwc481132mx4l83kwbpby331y2j5vv-python3.6-dogpile.cache-0.6.4/lib/python3.6/site-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/nix/store/81lwc481132mx4l83kwbpby331y2j5vv-python3.6-dogpile.cache-0.6.4/lib/python3.6/site-packages/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/nix/store/81lwc481132mx4l83kwbpby331y2j5vv-python3.6-dogpile.cache-0.6.4/lib/python3.6/site-packages/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/nix/store/81lwc481132mx4l83kwbpby331y2j5vv-python3.6-dogpile.cache-0.6.4/lib/python3.6/site-packages/dogpile/cache/region.py", line 800, in gen_value
    created_value = creator()
  File "/nix/store/81lwc481132mx4l83kwbpby331y2j5vv-python3.6-dogpile.cache-0.6.4/lib/python3.6/site-packages/dogpile/cache/region.py", line 1227, in creator
    return fn(*arg, **kw)
  File "/nix/store/hn9sswpyglcwjgyg5g2jnrq1n2f50rfz-nox-0.0.6/lib/python3.6/site-packages/nox/nixpkgs_repo.py", line 91, in packages_for_sha
    return packages(repo.path)
  File "/nix/store/hn9sswpyglcwjgyg5g2jnrq1n2f50rfz-nox-0.0.6/lib/python3.6/site-packages/nox/nixpkgs_repo.py", line 82, in packages
    universal_newlines=True)
  File "/nix/store/53dyjh7xjhnbibqllr7j27lk2h98n7j7-python3-3.6.4/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/nix/store/53dyjh7xjhnbibqllr7j27lk2h98n7j7-python3-3.6.4/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nix-env', '-f', '/home/andi/.nox/nixpkgs', '-qaP', '--out-path', '--show-trace']' returned non-zero exit status 1.
```

Details about my system:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.2, NixOS, 18.03.git.87059c2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0pre5889_c287d731`
 - channels(root): `"nixos-18.03pre126729.2e4aded3669, nixos-17.09-17.09.2948.fc2f32394cf"`
 - channels(andi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by andir** [comment]
This has probably been fixed with https://github.com/mozilla/nixpkgs-mozilla/commit/5ed3b4f96167fab48f48c24ac913470a77d8fad4. I will test this in a bit.
